services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prettysecurerootpassword
      MYSQL_DATABASE: backy-db
      MYSQL_USER: backy-user
      MYSQL_PASSWORD: prettysecurepassword
    ports:
      - 3306:3306
